name: build

on:
  push:
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"
  pull_request:

env:
  IMAGE_NAME: steled/bitnami-shell

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v3
#        with:
#          images: ${{ env.IMAGE_NAME }}
#          labels: |
#            org.opencontainers.image.source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
#            org.opencontainers.image.revision=${GITHUB_SHA}
#            org.opencontainers.image.created=$(date --rfc-3339=seconds)
#          tags: |
#            latest
#            debian

#      - name: Build image
#        run: |
#          docker build . \
#            --pull=true \
#            --file=Dockerfile \
#            --tag="${{ env.IMAGE_NAME }}:latest" \
#            --tag="${{ env.IMAGE_NAME }}:debian" \
#            --label="org.opencontainers.image.source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
#            --label="org.opencontainers.image.revision=${GITHUB_SHA}" \
#            --label="org.opencontainers.image.created=$(date --rfc-3339=seconds)"

#      - name: Test image
#        run: tests/run ${{ env.IMAGE_NAME }}:debian

      - name: Login to Dockerhub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: Dockerfile
#          push: true
#          labels: ${{ steps.meta.outputs.labels }}
#          tags: ${{ steps.meta.outputs.tags }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and publish arm64 images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: 10/debian-10/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            steled/bitnami-shell:debian-arm64
            steled/bitnami-shell:latest-arm64
            steled/bitnami-shell:${{ github.ref_name }}